[project]
name = "see-house-api"
version = "1.0.0"
description = "California housing price prediction API using FastAPI and Random Forest"
requires-python = ">=3.12,<3.13"


dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "notebook",
    "jupyter",
    "fastapi[standard]",
    "streamlit",
    "skops",
]

[tool.uv]
package = false

[tool.fastapi]
entrypoint = "main:app"