[project]
name = "see-house-api"
version = "1.0.0"
description = "California housing price prediction API using FastAPI and Random Forest"
requires-python = ">=3.12,<3.13"

dependencies = [
    "fastapi[standard]",
    "numpy",
    "scikit-learn",
    "skops",
]

[tool.uv]
package = false

[tool.fastapi]
entrypoint = "main:app"